apiVersion: apps/v1
kind: Deployment
metadata:
  name: starter-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: starter
  template:
    metadata:
      labels:
        app: starter
    spec:
      containers:
        - name: starter
          image: 344299758316.dkr.ecr.us-east-1.amazonaws.com/starter-repo:latest
          ports:
            - containerPort: 3030


---
apiVersion: v1
kind: Service
metadata:
  name: starter-service
spec:
  selector:
    app: starter
  ports:
    - name: http
      port: 3030
      targetPort: 3030
  type: ClusterIP