apiVersion: v1
clusters:
  - cluster:
      certificate-authority: /System/Volumes/Data/Users/ifedayo/.minikube/ca.crt
      server: https://192.168.99.100:8443
    name: minikube
contexts:
  - context:
      cluster: minikube
      user: minikube
    name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
  - name: minikube
    user:
      client-certificate: /System/Volumes/Data/Users/ifedayo/.minikube/proxy-client-ca.key
      client-key: /System/Volumes/Data/Users/ifedayo/.minikube/proxy-client-ca.key