name: Hello-Workflow-CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: latest

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: hello-workflow:${{ env.GITHUB_SHA }}

    - name: Deploy to Temporal
      uses: actions/aws-cli@v2
      with:
        args: deploy
        command: temporal
        env:
          AWS_REGION: us-west-2
