name: Deploy to EKS

on:
  push:
    branches:
      - main

env:
  K8S_NAMESPACE: default
  K8S_DEPLOYMENT_START: starter-deployment
  K8S_DEPLOYMENT_WORKER: worker-deployment
  ECR_REGISTRY: 344299758316.dkr.ecr.us-east-1.amazonaws.com

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build starter image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.ECR_REGISTRY }}/starter-repo:${{ env.GITHUB_SHA }}

    - name: Build worker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.ECR_REGISTRY }}/worker-repo:${{ env.GITHUB_SHA }}

    # - name: Apply Kubernetes Deployment for Starter
    #   uses: pulumi/actions/kubectl@v1
    #   with:
    #     args: apply -f deployments/starter-deployment.yml
    #     env:
    #       KUBECONFIG: ${{ secrets.KUBE_CONFIG }}
    
    # - name: Apply Kubernetes Deployment for Worker
    #   uses: pulumi/actions/kubectl@v1
    #   with:
    #     args: apply -f deployments/worker-deployment.yml
    #     env:
    #       KUBECONFIG: ${{ secrets.KUBE_CONFIG }}

    # - name: Update image in deployments.yml
    #   run: |
    #     kubectl set image deployment/starter starter=${{ env.ECR_REGISTRY }}/starter-repo:${{ env.GITHUB_SHA }}
    #     kubectl set image deployment/worker worker=${{ env.ECR_REGISTRY }}/worker-repo:${{ env.GITHUB_SHA }}
