name: CI/CD

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-west-2
  AWS_ACCOUNT_ID: 344299758316
  DOCKER_IMAGE_STAGER: hello-starter
  DOCKER_IMAGE_WORKER: hello-worker
  ECR_REPOSITORY_STAGER: starter-repo
  ECR_REPOSITORY_WORKER: worker-repo

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIAVAKO5MLWOPQZQ6HW
        aws-secret-access-key: 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
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: ${{ env.AWS_REGION }}

    - name: Build starter image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: hello-starter

    - name: Push starter image to Amazon ECR
      uses: aws-actions/amazon-ecr-push@v1
      with:
        tags: hello-starter
        repository-url: public.ecr.aws/z4w2w9k3/starter-repo
      env:
        AWS_REGISTRY_AUTH: ${{ steps.login-ecr.outputs.registry-auth }}

    - name: Build worker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: hello-worker

    - name: Push worker image to Amazon ECR
      uses: aws-actions/amazon-ecr-push@v1
      with:
        tags: hello-worker
        repository-url: public.ecr.aws/z4w2w9k3/worker-repo
      env:
        AWS_REGISTRY_AUTH: ${{ steps.login-ecr.outputs.registry-auth }}
