name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-west-2

jobs:
  build-worker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Worker Docker image
      uses: docker/build-push-action@v2
      with:
        context: worker
        tags: $(aws ecr describe-repositories --repository-name worker-repo --region ${{ env.AWS_REGION }} --query "repositories[].repositoryUri" --output text)/worker-image:${{ env.GITHUB_SHA }}
        push: true

  build-starter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Starter Docker image
      uses: docker/build-push-action@v2
      with:
        context: starter
        tags: $(aws ecr describe-repositories --repository-name starter-repo --region ${{ env.AWS_REGION }} --query "repositories[].repositoryUri" --output text)/starter-image:${{ env.GITHUB_SHA }}
        push: true

  deploy:
    runs-on: ubuntu-latest
    needs: [build-worker, build-starter]
    if: success()

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Apply Worker deployment
      uses: kubernetes-actions/kubectl@v1
      with:
        args: set image deployment/worker worker=worker-repo/worker-image:${{ env.GITHUB_SHA }}

    - name: Apply Starter deployment
      uses: kubernetes-actions/kubectl@v1
      with:
        args: set image deployment/starter starter=starter-repo/starter-image:${{ env.GITHUB_SHA }}
