name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-west-2

jobs:
  build-worker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install awscli

    - name: Build and push Worker Docker image
      uses: docker/build-push-action@v2
      with:
        context: worker
        tags: worker-repo/hello-worker:latest
        push: true

  build-starter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install awscli

    - name: Build and push Starter Docker image
      uses: docker/build-push-action@v2
      with:
        context: starter
        tags: starter-repo/hello-starter:latest
        push: true

  deploy:
    runs-on: ubuntu-latest
    needs: [build-worker, build-starter]
    if: success()

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Apply Worker deployment
      uses: kubernetes-actions/kubectl@v1
      with:
        args: set image deployment/worker worker=worker-repo/worker-image:${{ env.GITHUB_SHA }}

    - name: Apply Starter deployment
      uses: kubernetes-actions/kubectl@v1
      with:
        args: set image deployment/starter starter=starter-repo/starter-image:${{ env.GITHUB_SHA }}
