name: CI/CD

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-west-2
  AWS_ACCOUNT_ID: 344299758316
  DOCKER_IMAGE_STAGER: hello-starter
  DOCKER_IMAGE_WORKER: hello-worker
  ECR_REPOSITORY_STAGER: starter-repo
  ECR_REPOSITORY_WORKER: worker-repo

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: ${{ env.AWS_REGION }}

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: |
          ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY_STAGER }}:${{ env.DOCKER_IMAGE_STAGER }}
          ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY_WORKER }}:${{ env.DOCKER_IMAGE_WORKER }}
        push: true
        dockerfile: |
          Dockerfile.starter
          Dockerfile.worker
