name: Deployment Update

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-west-2

jobs:
  build-worker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Worker Docker image
      uses: docker/build-push-action@v2
      with:
        context: worker
        tags: worker-repo/hello-worker:${{ env.GITHUB_SHA }}
        push: true

  build-starter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Starter Docker image
      uses: docker/build-push-action@v2
      with:
        context: starter
        tags: starter-repo/hello-starter:${{ env.GITHUB_SHA }}
        push: true

  deploy:
    runs-on: ubuntu-latest
    needs: [build-worker, build-starter]
    if: success()

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIAVAKO5MLWOPQZQ6HW
        aws-secret-access-key: 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
        aws-region: ${{ env.AWS_REGION }}

    - name: Apply Worker deployment
      uses: kubernetes-actions/kubectl@v1
      with:
        args: set image deployment/worker worker=worker-repo/hello-worker:${{ env.GITHUB_SHA }}

    - name: Apply Starter deployment
      uses: kubernetes-actions/kubectl@v1
      with:
        args: set image deployment/starter starter=starter-repo/hello-starter:${{ env.GITHUB_SHA }}
