name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-west-2
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: latest

    - name: Install AWS CLI
      uses: aws-actions/setup-aws-cli@v1
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Build Temporal Starter
      run: |
        docker build -t hello-starter -f Dockerfile.starter .
        export REPOSITORY=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/hello-starter
        $(aws ecr get-login --region $AWS_REGION --no-include-email)
        docker tag hello-starter $REPOSITORY
        docker push $REPOSITORY

    - name: Build Temporal Worker
      run: |
        docker build -t hello-worker -f Dockerfile.worker .
        export REPOSITORY=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/hello-worker
        $(aws ecr get-login --region $AWS_REGION --no-include-email)
        docker tag hello-worker $REPOSITORY
        docker push $REPOSITORY